### ISSUE TITLE
The meaning of "eval == False"

### ISSUE THREAD

**Issue by xxwywzy** [RickardKarl/bill-the-bot#2]
Hi, thank you for posting such a great code for implementing Q-learning. I hava a small question for the code, In the line 60 of "simulation.py", what's the meanning of "eval == False"? I think updateQ should be True here.

**Comment by RickardKarl** [comment]
Hi, I happy to hear that you enjoy the code. I believe that you actually found an error in my code, you are right that updateQ should be True. This is an artefact from some experiments that I did, but I will correct this. Thanks for pointing this out!
