### ISSUE TITLE
Only agent1 gets saved, even if agent2 has a higher win rate

### ISSUE THREAD

**Issue by Piratenlulasch** [RickardKarl/bill-the-bot#4]
A friend of mine just showed me your Code. I'm not familiar with Q-learning at all, but I know a little bit about coding.

It seems like, regardless of which agent actually has the higher win rate, only `agent1` will get saved. Maybe that's the point, just wondering.

And you save both agents, which are returned by `simulate()`, in variables in `trainPlayerX.py` but you don't do anything with those variables do you?

**Comment by RickardKarl** [comment]
Closing issue. Thanks for the update!
